### PR TITLE
Add `DfTx` PoolCreatePair

### PR DESCRIPTION
**Pull request by canonbrother**
#### What kind of PR is this?:

/kind feature

#### Which issue(s) does this PR fixes?:

Fixes part of #108

### CODE REVIEW

**Review by fuxingloh — CHANGES_REQUESTED** [review]

**Comment by fuxingloh** [comment]
I realized I didn't see out my review after marking it as draft.

Anyway this might help:
https://mainnet.defichain.io/#/DFI/mainnet/tx/

1. f3c99e199d0157b2b6254cf3a51bb1171569ad5c4beb797e957d245aec194d38
2. 9827894c083b77938d13884f0404539daa054a818e0c5019afa1eeff0437a51b
3. 37939243c7dbacb2675cfc4e0632e9bf829dcc5cece2928f235fba4b03c09a6a
4. 9e0c956f9c626c07ba3dd742748ff9872b5688a976d66d35aa09418f18620b64
5. 75a25a52c54d12f84d4a553be354fa2c5651689d8f9f4860aad8b68c804af3f1
6. 84ef6a6733dd97d2d4b963ad99ab26829d58f4ab913dafb9cc7c84885f783854

**Comment by canonbrother** [comment]
> I realized I didn't sent out my review after marking it as draft.
> 
> Anyway these txid might help:
> https://mainnet.defichain.io/#/DFI/mainnet/tx/
> 
>     1. f3c99e199d0157b2b6254cf3a51bb1171569ad5c4beb797e957d245aec194d38
> 
>     2. 9827894c083b77938d13884f0404539daa054a818e0c5019afa1eeff0437a51b
> 
>     3. 37939243c7dbacb2675cfc4e0632e9bf829dcc5cece2928f235fba4b03c09a6a
> 
>     4. 9e0c956f9c626c07ba3dd742748ff9872b5688a976d66d35aa09418f18620b64
> 
>     5. 75a25a52c54d12f84d4a553be354fa2c5651689d8f9f4860aad8b68c804af3f1
> 
>     6. 84ef6a6733dd97d2d4b963ad99ab26829d58f4ab913dafb9cc7c84885f783854

yea great.. wondering how you get these though??

**Comment by canonbrother** [comment]
### Issue Facing: Inconsistent hex - `010000` (undefined) vs `0100` (nothing)
```
mainnet
6a2b44665478700200400d0300000000001976a9148f83f4f005ba70f0c5d7a59d4696daee13a6e43b88ac0100
6a2c44665478700900400d0300000000001976a9148f83f4f005ba70f0c5d7a59d4696daee13a6e43b88ac010000

regtest 
6a2a4466547870000200e1f5050000000017a914462093ba56448f9b6d1d22584b3236e2555432d487010000
'{ "tokenA": "DFI", "tokenB": "BAT", "commission": 1, "status": true, "ownerAddress": "2N1GtCarydVoEnr8vjhLgBDxwDT7tauLXZf"}'
```

I managed to generate `0100` while I re-spin up the regtest with `-clarkequayheight=3000000` to purposely skip the `rewards` get included
https://github.com/DeFiCh/ain/blob/e3db4110f2bcb41b4ae2d49e3fb669d11ce5cca8/src/masternodes/rpc_poolpair.cpp#L571-L573

**Comment by fuxingloh** [comment]
> ### Issue Facing: Inconsistent hex - `010000` (undefined) vs `0100` (nothing)
> ```
> mainnet
> 6a2b44665478700200400d0300000000001976a9148f83f4f005ba70f0c5d7a59d4696daee13a6e43b88ac0100
> 6a2c44665478700900400d0300000000001976a9148f83f4f005ba70f0c5d7a59d4696daee13a6e43b88ac010000
> 
> regtest 
> 6a2a4466547870000200e1f5050000000017a914462093ba56448f9b6d1d22584b3236e2555432d487010000
> '{ "tokenA": "DFI", "tokenB": "BAT", "commission": 1, "status": true, "ownerAddress": "2N1GtCarydVoEnr8vjhLgBDxwDT7tauLXZf"}'
> ```
> 
> I managed to simulate `0100` while I spinned up the regtest with `-clarkequayheight=3000000` to skip the `rewards`
> https://github.com/DeFiCh/ain/blob/e3db4110f2bcb41b4ae2d49e3fb669d11ce5cca8/src/masternodes/rpc_poolpair.cpp#L571-L573
> 
> #### Optional handling is not doable because of "undefined" vs "nothing"
> the `rewards: undefined` will still output `00` as our consistent composers design
> 
> ```
> return [
>   ...
>   ComposableBuffer.varUIntArray(() => p.customRewards, v => p.customRewards = v, v => new CTokenBalance(v))
> ]
> ```
> 
> #### Odd solution for `0100`
> spin up a testcontainer with `-clarkequayheight={high figure}` with createpoolpair composer without reward handling

Thanks for the detailed explanation, I don't have a good solution for this yet without adding in extreme complexity to this `DfTx`. We should keep this drafted for now, and revisit it later.

**Review by fuxingloh — DISMISSED** [review]

**Review by monstrobishi — DISMISSED** [review]

**Comment by fuxingloh** [comment]
Need to fix conflicts for this

**Review by fuxingloh — APPROVED** [review]

**Review by monstrobishi — APPROVED** [review]

**Pull request merged**
