### PR TITLE
PoolSwap `maxPrice` default value handling

### LINKED ISSUE #494: PoolSwap `toOpCodes` failed to read
#### What happened:
```sh
Too many decimals read from buffer. Will lose precision with more than 8 decimals

      554 |         const fraction = readBigNumberUInt64(buffer)
      555 |         if (fraction.gt(new BigNumber('99999999'))) {
    > 556 |           throw new Error('Too many decimals read from buffer. Will lose precision with more than 8 decimals')
          |                 ^
      557 |         }
      558 |         setter(integer.plus(fraction.dividedBy(ONE_HUNDRED_MILLION)))
      559 |       },
```

#### What you expected to happen:
Previously code is working, guessing the issue was caused by recent update #469

#### How to reproduce it (as minimally and precisely as possible):
https://mainnet.defichain.io/#/DFI/mainnet/tx/700473ec7ca4f6bec261e75342f91825f3c2cf60df1bf1f335b53a2bcd95b994
6a4c4f446654787317a9140806eb42b6d5bb69726909fb6da34a9152afdf048701c7b3240d0000000017a9140806eb42b6d5bb69726909fb6da34a9152afdf048700ffffffffffffff7fffffffffffffff7f

### PR DESCRIPTION
**Pull request by canonbrother**
#### What kind of PR is this?:

/kind fix

#### What this PR does / why we need it:
Added new handling for null value maxPrice which will be given a `max int64` default value

#### Which issue(s) does this PR fixes?:

Fixes #494

### CODE REVIEW

**Comment by canonbrother** [comment]
codeclimate :sweat:

**Comment by Jouzo** [comment]
We can use MAX_INT64 but the 'poolswap' call does not accept anything above 1200000000 as tested in 
`packages/jellyfish-api-core/__tests__/category/poolpair/poolSwapMaxPrice.test.ts`

**Comment by canonbrother** [comment]
> poolSwapMaxPrice

yea its fine, we just need to special handle the maxPrice default value (max int64)

**Comment by canonbrother** [comment]
> We can use MAX_INT64 but the 'poolswap' call does not accept anything above 1200000000 as tested in
> `packages/jellyfish-api-core/__tests__/category/poolpair/poolSwapMaxPrice.test.ts`

yea its fine, we just need to special handle the maxPrice default value (max int64)

**Review by fuxingloh — APPROVED** [review]

**Review by ivan-zynesis — APPROVED** [review]

**Pull request merged**
