### PR TITLE
Automatic Conversion of Integer/Fraction for MaxPrice in dftx_pool.ts

### LINKED ISSUE #439: Automatic Conversion of Integer/Fraction for MaxPrice in `dftx_pool.ts`
#### What would you like to be added:

Automatically convert Integer & Fraction to their correct implementation. This allows easier use of MaxPrice without having to convert it yourself. #429 is partially flawed PR.

1. `maxPrice = integer * PRECISION + fraction`
2. PRECISION is fixed to `100000000`
3. therefore maxPrice of A/B trade 100/50 = `2.0` would be an integer of `2` and fraction of 0
4. or an integer of `0` and a fraction of `200000000`
5. with basic arithmetic, you can get max price automatically from floating-point numbers

https://github.com/DeFiCh/jellyfish/blob/78f2509421c86e29da77c771cd6371044f5e5fbb/packages/jellyfish-transaction/src/script/defi/dftx_pool.ts#L43-L54

Also, to rename https://github.com/DeFiCh/jellyfish/tree/main/packages/jellyfish-transaction/src/script/defi directory to `dftx`.

/triage accepted
/area jellyfish-transaction
/priority urgent-now

### PR DESCRIPTION
**Pull request by Jouzo**
#### What kind of PR is this?:
/kind fix
/kind refactor

#### What this PR does / why we need it:

Automatic Conversion of Integer/Fraction for MaxPrice in `dftx_pool.ts` 
refactoring packages/jellyfish-transaction/src/script/defi -> packages/jellyfish-transaction/src/script/dftx
refactoring packages/jellyfish-transaction/__tests__/script/defi -> packages/jellyfish-transaction/__tests__/script/dftx

#### Which issue(s) does this PR fixes?:
Fixes #439

### CODE REVIEW

**Comment by Jouzo** [comment]
Impacts PR #429. 
txn_builder_dex_poolswap in jellyfish-transaction-builder should be updated to match new PoolSwap interface.

**Comment by fuxingloh** [comment]
Need to use BigNumber, check this out: https://github.com/DeFiCh/jellyfish/issues/18

To separate the `dftx` refactor changes into another PR, easier to review.

**Comment by Jouzo** [comment]
maxPrice typed as BigNumber ?

Ok, I will do another branch for the refactoring

**Comment by fuxingloh** [comment]
> maxPrice typed as BigNumber ?
> 
> Ok, I will do another branch for the refactoring

yup `BigNumber`

**Pull request closed without merging**
