### PR TITLE
Automatic Conversion of Integer/Fraction for MaxPrice in dftx_pool.ts

### LINKED ISSUE #439: Automatic Conversion of Integer/Fraction for MaxPrice in `dftx_pool.ts`
#### What would you like to be added:

Automatically convert Integer & Fraction to their correct implementation. This allows easier use of MaxPrice without having to convert it yourself. #429 is partially flawed PR.

1. `maxPrice = integer * PRECISION + fraction`
2. PRECISION is fixed to `100000000`
3. therefore maxPrice of A/B trade 100/50 = `2.0` would be an integer of `2` and fraction of 0
4. or an integer of `0` and a fraction of `200000000`
5. with basic arithmetic, you can get max price automatically from floating-point numbers

https://github.com/DeFiCh/jellyfish/blob/78f2509421c86e29da77c771cd6371044f5e5fbb/packages/jellyfish-transaction/src/script/defi/dftx_pool.ts#L43-L54

Also, to rename https://github.com/DeFiCh/jellyfish/tree/main/packages/jellyfish-transaction/src/script/defi directory to `dftx`.

/triage accepted
/area jellyfish-transaction
/priority urgent-now

### PR DESCRIPTION
**Pull request by Jouzo**
#### What kind of PR is this?:

/kind fix

#### What this PR does / why we need it:

Automatic Conversion of Integer/Fraction for MaxPrice in dftx_pool.ts

#### Which issue(s) does this PR fixes?:

Fixes #439

### CODE REVIEW

**Comment by Jouzo** [comment]
It seems that we need the `fuxingloh/testcontainer-block-gen-0` merged into main before merging this one

**Comment by fuxingloh** [comment]
> It seems that we need the `fuxingloh/testcontainer-block-gen-0` merged into main before merging this one

You had a previous PR you created that was targeting `main` with maxPrice implementation?
We need that PR that has the base branch as `main`, I need that fix to do a release soon.

**Comment by fuxingloh** [comment]
image

you broke it when you retargeted it

**Comment by Jouzo** [comment]
Can't reopen the merged PR

**Comment by fuxingloh** [comment]
image
drop these commits

**Comment by Jouzo** [comment]
dropped

**Review by ivan-zynesis — APPROVED** [review]

**Review by jingyi2811 — APPROVED** [review]

**Review by fuxingloh — APPROVED** [review]

**Pull request merged**
